//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Utils.Path Utilities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category1_PathUtils {
            get {
                return ResourceManager.GetString("Category1_PathUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Utils.String Utilities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category1_StringUtils {
            get {
                return ResourceManager.GetString("Category1_StringUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line feed code to be set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category5_ConvertCRLF_CRLF {
            get {
                return ResourceManager.GetString("Category5_ConvertCRLF_CRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path Array に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CombineDesigner_Label {
            get {
                return ResourceManager.GetString("CombineDesigner_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converts the specified string, which encodes binary data as base-64 digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_Base64Decode {
            get {
                return ResourceManager.GetString("Description3_Base64Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converts a String to its equivalent string representation that is encoded with base-64 digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_Base64Encode {
            get {
                return ResourceManager.GetString("Description3_Base64Encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converts a String to its equivalent string representation that is encoded with base-64 digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_Base64EncodeFromFile {
            get {
                return ResourceManager.GetString("Description3_Base64EncodeFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combines an array of strings into a path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_Combine {
            get {
                return ResourceManager.GetString("Description3_Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert the line feed code of the given text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_ConvertCRLF {
            get {
                return ResourceManager.GetString("Description3_ConvertCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets the current working directory. only calls Directory.GetCurrentDirectory method. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_CurrentDir {
            get {
                return ResourceManager.GetString("Description3_CurrentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns the absolute path for the specified path string ,checks the existence of the file ,etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_PathUtils {
            get {
                return ResourceManager.GetString("Description3_PathUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An activity that converts arbitrary objects to JSON strings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3_ToJSONString {
            get {
                return ResourceManager.GetString("Description3_ToJSONString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the String to be decoded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_Base64Decode_Target {
            get {
                return ResourceManager.GetString("Description4_Base64Decode_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the String to be encoded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_Base64Encode_Target {
            get {
                return ResourceManager.GetString("Description4_Base64Encode_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the file path of the file to be  encoded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_Base64EncodeFromFile_Path {
            get {
                return ResourceManager.GetString("Description4_Base64EncodeFromFile_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An array of parts of the path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_Combine_PathArray {
            get {
                return ResourceManager.GetString("Description4_Combine_PathArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the String to be converted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_ConvertCRLF_Target {
            get {
                return ResourceManager.GetString("Description4_ConvertCRLF_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns  the current working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_CurrentDir_FullPath {
            get {
                return ResourceManager.GetString("Description4_CurrentDir_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns the same as Path.GetDirectoryName().If an existing directory is specified, even if there is no &quot;\&quot; at the end, the directory name is returned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_PathUtils_DirectoryName {
            get {
                return ResourceManager.GetString("Description4_PathUtils_DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if the specified Directory exists (returns false even if it exists if it is a File). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_PathUtils_DirExists {
            get {
                return ResourceManager.GetString("Description4_PathUtils_DirExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if the specified File exists (returns false even if it exists if it is a Directory). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_PathUtils_FileExists {
            get {
                return ResourceManager.GetString("Description4_PathUtils_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns full Path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_PathUtils_FullPath {
            get {
                return ResourceManager.GetString("Description4_PathUtils_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the file path as a string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4_PathUtils_Path {
            get {
                return ResourceManager.GetString("Description4_PathUtils_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base64 Decode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_Base64Decode {
            get {
                return ResourceManager.GetString("DisplayName2_Base64Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base64 Encode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_Base64Encode {
            get {
                return ResourceManager.GetString("DisplayName2_Base64Encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base64 Encode From File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_Base64EncodeFromFile {
            get {
                return ResourceManager.GetString("DisplayName2_Base64EncodeFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_Combine {
            get {
                return ResourceManager.GetString("DisplayName2_Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert CR/LF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_ConvertCRLF {
            get {
                return ResourceManager.GetString("DisplayName2_ConvertCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_CurrentDir {
            get {
                return ResourceManager.GetString("DisplayName2_CurrentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path Utils に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_PathUtils {
            get {
                return ResourceManager.GetString("DisplayName2_PathUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To JSON String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2_ToJSONString {
            get {
                return ResourceManager.GetString("DisplayName2_ToJSONString", resourceCulture);
            }
        }
    }
}
