//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Specify the String to be decoded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Base64Decode_Description {
            get {
                return ResourceManager.GetString("Base64Decode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the String to be encoded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Base64Encode_Description {
            get {
                return ResourceManager.GetString("Base64Encode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the file path of the file to be  encoded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Base64EncodeFromFile_Description {
            get {
                return ResourceManager.GetString("Base64EncodeFromFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An array of parts of the path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Combine_Description {
            get {
                return ResourceManager.GetString("Combine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path Array に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CombineDesigner_Label {
            get {
                return ResourceManager.GetString("CombineDesigner_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line feed code to be set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertCRLF_Category {
            get {
                return ResourceManager.GetString("ConvertCRLF_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the String to be converted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertCRLF_Description {
            get {
                return ResourceManager.GetString("ConvertCRLF_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns  the current working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentDir_Description {
            get {
                return ResourceManager.GetString("CurrentDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns the same as Path.GetDirectoryName().If an existing directory is specified, even if there is no &quot;\&quot; at the end, the directory name is returned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathUtils_DirectoryName_Desc {
            get {
                return ResourceManager.GetString("PathUtils_DirectoryName_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if the specified Directory exists (returns false even if it exists if it is a File). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathUtils_DirExists_Desc {
            get {
                return ResourceManager.GetString("PathUtils_DirExists_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if the specified File exists (returns false even if it exists if it is a Directory). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathUtils_FileExists_Desc {
            get {
                return ResourceManager.GetString("PathUtils_FileExists_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns full Path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathUtils_FullPath_Desc {
            get {
                return ResourceManager.GetString("PathUtils_FullPath_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the file path as a string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathUtils_Path_Desc {
            get {
                return ResourceManager.GetString("PathUtils_Path_Desc", resourceCulture);
            }
        }
    }
}
